### PR TITLE
[SBT-013] Provide an option to users to instruct antlr to treat warnings as errors when generating the parser.

### PR DESCRIPTION
**Pull request by dilipbiswal**
Provide an option to users to instruct antlr to treat warnings as errors when generating the parser.

### CODE REVIEW

**Comment by dilipbiswal** [comment]
@ihji Thank you for creating the sbt-013 branch. I have created this on top of sbt-013. I am going to close the previous PR.

One question, would you please let me know whats the version of the plugin when its pushed to the repo ? i.e what should i have in the addSbtPlugin(...) on my end ? Thank you very much in advance.

**Comment by ihji** [comment]
@dilipbiswal Will be published as 0.8.2 and 0.7.13. 0.8.2 is already published and 0.7.13 is on track.

**Comment by dilipbiswal** [comment]
@ihji Got it. Thanks a lot.

**Comment by ihji** [comment]
LGTM. Thanks!

**Comment by dilipbiswal** [comment]
@ihji Thank you very much for speedy turn-around. Appreciate it very much !!

**Pull request merged**
